logging:
  level:
    root: ERROR
    io.lettuce: ERROR
    org.springframework: ERROR
    com.sypark.problem: ERROR

server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json

management.endpoints.web.exposure.include: "*"
management.endpoints.jmx.exposure.include: "*"
